### ISSUE TITLE
damaged or incomplete

### ISSUE THREAD

**Issue by maxwellhibbert** [LaunchPalette/Helper#1]
You can’t open the application “LaunchPalette.Helper.app” because it may be damaged or incomplete.

**Comment by seungwoochoe** [comment]
Hi, thank you for letting me know about it! The `LaunchPalette.Helper.app.zip` file should be unzipped by double-clicking it, rather than by removing the '.zip' from the file name. (I'm just guessing you might have done that because the app inside is named 'LaunchPalette Helper.app', not 'LaunchPalette.Helper.app'.)
